name: Server Module Java CI/CD with Maven

on:
  push:
    paths:
      - '**'
      - '.github/workflows/server.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven package
        run: mvn package --file pom.xml

      - name: Build Docker image
        run: docker build --build-arg GITHUB_REPO=${{ github.repository }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: deeeesp
          password: ${{ secrets.TOKEN }}

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: deeeesp
          password: ${{ secrets.TOKEN }}

      - name: deploy
        uses: okteto/pipeline@latest
        with:
          name: movie
          timeout: 8m
